Repository metal3-io/ironic-inspector-image, pull requests merged in 2019-11, with the labels that each got.

#42 IPv6 support for inspector
  Dockerfile
  inspector.conf
  ironic-common.sh
  runironic-inspector.sh
Labels: approved, lgtm, size/M

#39 Remove iptables filters from ironic-inspector containers
  Dockerfile
  runironic-inspector.sh
Labels: CI, approved, lgtm, size/S

#43 Sync ironic-common.sh with ironic-image
  ironic-common.sh
Labels: approved, lgtm, size/S
