Repository metal3-io/ironic-inspector-image, pull requests merged in 2020-07, with the labels that each got.

#60 Configure inspector to keep all ports found
  inspector.conf
Labels: approved, lgtm, size/XS

#59 Add http_basic auth support
  Dockerfile
  runironic-inspector.sh
Labels: approved, lgtm, size/S

#61 Simplify HTTP basic auth configuration
  Dockerfile
  runironic-inspector.sh
Labels: approved, lgtm, size/M
